# See https://embarkstudios.github.io/cargo-deny/checks/cfg.html for all configuration options
[graph]
targets = []
all-features = true
no-default-features = false

[output]
feature-depth = 1

[advisories]
db-path = "$CARGO_HOME/advisory-dbs"
db-urls = ["https://github.com/rustsec/advisory-db"]
ignore = [
    { id = "RUSTSEC-2024-0006", reason = "remove when shlex gets updated to >=1.3.0 (here and in nightly.yml)" },
    { id = "RUSTSEC-2024-0388", reason = "need to decide on replacement first as it is used in most paresec related projects" },
    { id = "RUSTSEC-2024-0404", reason = "required due to pinning of clap version due to MSRV" },

    # Due to older spiffe but upgrading will take some refactoring
    # { id = "RUSTSEC-2021-0139", reason = "ansi_term: remove once spiffe can be updated" },
    # { id = "RUSTSEC-2024-0375", reason = "atty: remove once spiffe can be updated" },
    # { id = "RUSTSEC-2021-0145", reason = "atty: remove once spiffe can be updated" },
    { id = "RUSTSEC-2024-0421", reason = "idna: remove once spiffe can be updated" },
    { id = "RUSTSEC-2024-0384", reason = "instant: remove once spiffe can be updated" },
]

[licenses]
allow = [
    "Apache-2.0",
    "Apache-2.0 WITH LLVM-exception",
    "BSD-3-Clause",
    "ISC",
    "LicenseRef-ring",
    "MIT",
    "Unicode-DFS-2016",
]
confidence-threshold = 0.8
exceptions = []

[[licenses.clarify]]
name = "ring"
expression = "LicenseRef-ring"
license-files = [
    { path = "LICENSE", hash = 0xbd0eed23 },
]

[licenses.private]
ignore = false

[bans]
multiple-versions = "warn"
wildcards = "allow"
highlight = "all"
workspace-default-features = "allow"
external-default-features = "allow"
allow = []
deny = []
skip = []

[sources]
unknown-registry = "warn"
unknown-git = "warn"
allow-registry = ["https://github.com/rust-lang/crates.io-index"]
