// Code generated by protoc-gen-go. DO NOT EDIT.
// source: create_key.proto

package create_key

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type OpCreateKeyProto struct {
	KeyName              string              `protobuf:"bytes,1,opt,name=key_name,json=keyName,proto3" json:"key_name,omitempty"`
	KeyAttributes        *KeyAttributesProto `protobuf:"bytes,2,opt,name=key_attributes,json=keyAttributes,proto3" json:"key_attributes,omitempty"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *OpCreateKeyProto) Reset()         { *m = OpCreateKeyProto{} }
func (m *OpCreateKeyProto) String() string { return proto.CompactTextString(m) }
func (*OpCreateKeyProto) ProtoMessage()    {}
func (*OpCreateKeyProto) Descriptor() ([]byte, []int) {
	return fileDescriptor_a71767776b682c50, []int{0}
}

func (m *OpCreateKeyProto) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OpCreateKeyProto.Unmarshal(m, b)
}
func (m *OpCreateKeyProto) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OpCreateKeyProto.Marshal(b, m, deterministic)
}
func (m *OpCreateKeyProto) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OpCreateKeyProto.Merge(m, src)
}
func (m *OpCreateKeyProto) XXX_Size() int {
	return xxx_messageInfo_OpCreateKeyProto.Size(m)
}
func (m *OpCreateKeyProto) XXX_DiscardUnknown() {
	xxx_messageInfo_OpCreateKeyProto.DiscardUnknown(m)
}

var xxx_messageInfo_OpCreateKeyProto proto.InternalMessageInfo

func (m *OpCreateKeyProto) GetKeyName() string {
	if m != nil {
		return m.KeyName
	}
	return ""
}

func (m *OpCreateKeyProto) GetKeyAttributes() *KeyAttributesProto {
	if m != nil {
		return m.KeyAttributes
	}
	return nil
}

type ResultCreateKeyProto struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ResultCreateKeyProto) Reset()         { *m = ResultCreateKeyProto{} }
func (m *ResultCreateKeyProto) String() string { return proto.CompactTextString(m) }
func (*ResultCreateKeyProto) ProtoMessage()    {}
func (*ResultCreateKeyProto) Descriptor() ([]byte, []int) {
	return fileDescriptor_a71767776b682c50, []int{1}
}

func (m *ResultCreateKeyProto) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ResultCreateKeyProto.Unmarshal(m, b)
}
func (m *ResultCreateKeyProto) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ResultCreateKeyProto.Marshal(b, m, deterministic)
}
func (m *ResultCreateKeyProto) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ResultCreateKeyProto.Merge(m, src)
}
func (m *ResultCreateKeyProto) XXX_Size() int {
	return xxx_messageInfo_ResultCreateKeyProto.Size(m)
}
func (m *ResultCreateKeyProto) XXX_DiscardUnknown() {
	xxx_messageInfo_ResultCreateKeyProto.DiscardUnknown(m)
}

var xxx_messageInfo_ResultCreateKeyProto proto.InternalMessageInfo

func init() {
	proto.RegisterType((*OpCreateKeyProto)(nil), "create_key.OpCreateKeyProto")
	proto.RegisterType((*ResultCreateKeyProto)(nil), "create_key.ResultCreateKeyProto")
}

func init() { proto.RegisterFile("create_key.proto", fileDescriptor_a71767776b682c50) }

var fileDescriptor_a71767776b682c50 = []byte{
	// 151 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x48, 0x2e, 0x4a, 0x4d,
	0x2c, 0x49, 0x8d, 0xcf, 0x4e, 0xad, 0xd4, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0xe2, 0x42, 0x88,
	0x48, 0x89, 0x64, 0xa7, 0x56, 0xc6, 0x27, 0x96, 0x94, 0x14, 0x65, 0x26, 0x95, 0x96, 0xa4, 0x16,
	0x43, 0x54, 0x28, 0x55, 0x70, 0x09, 0xf8, 0x17, 0x38, 0x83, 0x55, 0x79, 0xa7, 0x56, 0x06, 0x80,
	0x75, 0x49, 0x72, 0x71, 0x80, 0xd4, 0xe6, 0x25, 0xe6, 0xa6, 0x4a, 0x30, 0x2a, 0x30, 0x6a, 0x70,
	0x06, 0xb1, 0x67, 0xa7, 0x56, 0xfa, 0x25, 0xe6, 0xa6, 0x0a, 0x79, 0x72, 0xf1, 0xa1, 0x1a, 0x23,
	0xc1, 0xa4, 0xc0, 0xa8, 0xc1, 0x6d, 0xa4, 0xa4, 0x87, 0x66, 0xba, 0x77, 0x6a, 0xa5, 0x23, 0x9c,
	0x07, 0x36, 0x36, 0x88, 0x37, 0x1b, 0x59, 0x4c, 0x49, 0x8c, 0x4b, 0x24, 0x28, 0xb5, 0xb8, 0x34,
	0xa7, 0x04, 0xd5, 0xf6, 0x24, 0x36, 0xb0, 0xc3, 0x8c, 0x01, 0x01, 0x00, 0x00, 0xff, 0xff, 0xb4,
	0x53, 0xcb, 0x58, 0xce, 0x00, 0x00, 0x00,
}
