// Code generated by protoc-gen-go. DO NOT EDIT.
// source: asym_sign.proto

package asym_sign

import (
	fmt "fmt"
	math "math"

	"github.com/docker/parsec/client/operations/key_attributes"
	proto "github.com/golang/protobuf/proto"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type OpAsymmetricSignProto struct {
	KeyName              string                     `protobuf:"bytes,1,opt,name=key_name,json=keyName,proto3" json:"key_name,omitempty"`
	KeyLifetime          key_attributes.KeyLifetime `protobuf:"varint,2,opt,name=key_lifetime,json=keyLifetime,proto3,enum=key_attributes.KeyLifetime" json:"key_lifetime,omitempty"`
	Hash                 []byte                     `protobuf:"bytes,3,opt,name=hash,proto3" json:"hash,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                   `json:"-"`
	XXX_unrecognized     []byte                     `json:"-"`
	XXX_sizecache        int32                      `json:"-"`
}

func (m *OpAsymmetricSignProto) Reset()         { *m = OpAsymmetricSignProto{} }
func (m *OpAsymmetricSignProto) String() string { return proto.CompactTextString(m) }
func (*OpAsymmetricSignProto) ProtoMessage()    {}
func (*OpAsymmetricSignProto) Descriptor() ([]byte, []int) {
	return fileDescriptor_8a7f8666fa9709b2, []int{0}
}

func (m *OpAsymmetricSignProto) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OpAsymmetricSignProto.Unmarshal(m, b)
}
func (m *OpAsymmetricSignProto) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OpAsymmetricSignProto.Marshal(b, m, deterministic)
}
func (m *OpAsymmetricSignProto) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OpAsymmetricSignProto.Merge(m, src)
}
func (m *OpAsymmetricSignProto) XXX_Size() int {
	return xxx_messageInfo_OpAsymmetricSignProto.Size(m)
}
func (m *OpAsymmetricSignProto) XXX_DiscardUnknown() {
	xxx_messageInfo_OpAsymmetricSignProto.DiscardUnknown(m)
}

var xxx_messageInfo_OpAsymmetricSignProto proto.InternalMessageInfo

func (m *OpAsymmetricSignProto) GetKeyName() string {
	if m != nil {
		return m.KeyName
	}
	return ""
}

func (m *OpAsymmetricSignProto) GetKeyLifetime() key_attributes.KeyLifetime {
	if m != nil {
		return m.KeyLifetime
	}
	return key_attributes.KeyLifetime_Volatile
}

func (m *OpAsymmetricSignProto) GetHash() []byte {
	if m != nil {
		return m.Hash
	}
	return nil
}

type ResultAsymmetricSignProto struct {
	Signature            []byte   `protobuf:"bytes,1,opt,name=signature,proto3" json:"signature,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ResultAsymmetricSignProto) Reset()         { *m = ResultAsymmetricSignProto{} }
func (m *ResultAsymmetricSignProto) String() string { return proto.CompactTextString(m) }
func (*ResultAsymmetricSignProto) ProtoMessage()    {}
func (*ResultAsymmetricSignProto) Descriptor() ([]byte, []int) {
	return fileDescriptor_8a7f8666fa9709b2, []int{1}
}

func (m *ResultAsymmetricSignProto) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ResultAsymmetricSignProto.Unmarshal(m, b)
}
func (m *ResultAsymmetricSignProto) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ResultAsymmetricSignProto.Marshal(b, m, deterministic)
}
func (m *ResultAsymmetricSignProto) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ResultAsymmetricSignProto.Merge(m, src)
}
func (m *ResultAsymmetricSignProto) XXX_Size() int {
	return xxx_messageInfo_ResultAsymmetricSignProto.Size(m)
}
func (m *ResultAsymmetricSignProto) XXX_DiscardUnknown() {
	xxx_messageInfo_ResultAsymmetricSignProto.DiscardUnknown(m)
}

var xxx_messageInfo_ResultAsymmetricSignProto proto.InternalMessageInfo

func (m *ResultAsymmetricSignProto) GetSignature() []byte {
	if m != nil {
		return m.Signature
	}
	return nil
}

func init() {
	proto.RegisterType((*OpAsymmetricSignProto)(nil), "asym_sign.OpAsymmetricSignProto")
	proto.RegisterType((*ResultAsymmetricSignProto)(nil), "asym_sign.ResultAsymmetricSignProto")
}

func init() { proto.RegisterFile("asym_sign.proto", fileDescriptor_8a7f8666fa9709b2) }

var fileDescriptor_8a7f8666fa9709b2 = []byte{
	// 197 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x4f, 0x2c, 0xae, 0xcc,
	0x8d, 0x2f, 0xce, 0x4c, 0xcf, 0xd3, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0xe2, 0x84, 0x0b, 0x48,
	0x89, 0x64, 0xa7, 0x56, 0xc6, 0x27, 0x96, 0x94, 0x14, 0x65, 0x26, 0x95, 0x96, 0xa4, 0x16, 0x43,
	0x14, 0x28, 0xb5, 0x31, 0x72, 0x89, 0xfa, 0x17, 0x38, 0x16, 0x57, 0xe6, 0xe6, 0xa6, 0x96, 0x14,
	0x65, 0x26, 0x07, 0x67, 0xa6, 0xe7, 0x05, 0x80, 0xb5, 0x4a, 0x72, 0x71, 0x80, 0x74, 0xe4, 0x25,
	0xe6, 0xa6, 0x4a, 0x30, 0x2a, 0x30, 0x6a, 0x70, 0x06, 0xb1, 0x67, 0xa7, 0x56, 0xfa, 0x25, 0xe6,
	0xa6, 0x0a, 0xd9, 0x71, 0xf1, 0x80, 0xa4, 0x72, 0x32, 0xd3, 0x52, 0x4b, 0x32, 0x73, 0x53, 0x25,
	0x98, 0x14, 0x18, 0x35, 0xf8, 0x8c, 0xa4, 0xf5, 0xd0, 0x6c, 0xf0, 0x4e, 0xad, 0xf4, 0x81, 0x2a,
	0x09, 0xe2, 0xce, 0x46, 0x70, 0x84, 0x84, 0xb8, 0x58, 0x32, 0x12, 0x8b, 0x33, 0x24, 0x98, 0x15,
	0x18, 0x35, 0x78, 0x82, 0xc0, 0x6c, 0x25, 0x4b, 0x2e, 0xc9, 0xa0, 0xd4, 0xe2, 0xd2, 0x9c, 0x12,
	0x6c, 0x6e, 0x91, 0xe1, 0xe2, 0x04, 0xf9, 0x21, 0xb1, 0xa4, 0xb4, 0x08, 0xe2, 0x18, 0x9e, 0x20,
	0x84, 0x40, 0x12, 0x1b, 0xd8, 0x2b, 0xc6, 0x80, 0x00, 0x00, 0x00, 0xff, 0xff, 0xd2, 0x15, 0x81,
	0xcc, 0xfe, 0x00, 0x00, 0x00,
}
