name: "Load docker image"
description: "Load docker image"
inputs:
   image-name:
      required: true
      description: "Docker image name"
   image-path:
      required: true
      description: "Path to save the docker image"

runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v3
    - name: Download artifact
      uses: actions/download-artifact@v3
      with:
          name: ${{ inputs.image-name }}
          path: ${{ inputs.image-path }}
    - name: Load image
      run: docker load --input ${{ inputs.image-path }}/${{ inputs.image-name }}.tar
      shell: bash
